### PR TITLE
Add Arrow C Data Interface and nanoarrow dependency

### LINKED ISSUE #33: [DISCUSS] Columnar data protocol: Arrow or implement a new one?
A columnar data protocol is required in the following cases:

- Reading metadata from snapshot metadata (JSON, Avro)
- Writing metadata to snapshot metadata (JSON, Avro)
- Reading data from data files (Parquet, Avro, ORC)
- Writing data to data files (Parquet, Avro, ORC)

I'd like to use Arrow Array (backed by `nanoarrow`) for this purpose because

- It is the de-facto standard and accepted by many popular engines.
- [nanoarrow](https://github.com/apache/arrow-nanoarrow) library is lightweight and easy to use.

WDYT?

### PR DESCRIPTION
**Pull request by wgtmac**
Closes #33

### CODE REVIEW

**Comment by wgtmac** [comment]
I have managed to add `sparrow` as a vendored thirdparty dependency to `libiceberg`. However, there are still two issues that break CI:

1. It cannot compile on Windows due to `int128_t` is not supported by MSVC: https://github.com/apache/iceberg-cpp/actions/runs/13217571682/job/36898649736?pr=44.

```
D:\a\iceberg-cpp\iceberg-cpp\build\_deps\sparrow-src\include\sparrow\details\3rdparty\large_integers\int128_t.hpp(92,23): error C2065: 'int128_t': undeclared identifier [D:\a\iceberg-cpp\iceberg-cpp\build\_deps\sparrow-build\sparrow.vcxproj]
  (compiling source file '../sparrow-src/src/array_factory.cpp')
```

2. It cannot compile on MacOS with `AppleClang 15.0.0.15000309` since Sparrow README recommends `Apple Clang 16 or higher`: https://github.com/apache/iceberg-cpp/actions/runs/13217571682/job/36898649906?pr=44.

```
[  0%] Building CXX object _deps/sparrow-build/CMakeFiles/sparrow.dir/src/array_factory.cpp.o
In file included from /Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/src/array_factory.cpp:17:
In file included from /Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/include/sparrow/layout/decimal_array.hpp:24:
/Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/include/sparrow/buffer/u8_buffer.hpp:114:19: error: out-of-line definition of 'u8_buffer<T>' does not match any declaration in 'u8_buffer<T>'
    u8_buffer<T>::u8_buffer(R&& range)
                  ^~~~~~~~~
In file included from /Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/src/array_factory.cpp:19:
In file included from /Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/include/sparrow/layout/fixed_width_binary_array.hpp:17:
/Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/include/sparrow/layout/fixed_width_binary_layout/fixed_width_binary_array.hpp:336:83: error: no member named 'join' in namespace 'std::ranges::views'
        auto data_buffer = u8_buffer<values_inner_value_type>(std::ranges::views::join(values));
                                                              ~~~~~~~~~~~~~~~~~~~~^
/Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/include/sparrow/layout/fixed_width_binary_layout/fixed_width_binary_array.hpp:481:70: error: no member named 'join' in namespace 'std::ranges::views'
        const auto joined_repeated_value_range = std::ranges::views::join(my_repeat_view);
                                                 ~~~~~~~~~~~~~~~~~~~~^
In file included from /Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/src/array_factory.cpp:27:
/Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/include/sparrow/layout/variable_size_binary_layout/variable_size_binary_array.hpp:455:83: error: no member named 'join' in namespace 'std::ranges::views'
        auto data_buffer = u8_buffer<values_inner_value_type>(std::ranges::views::join(values));
                                                              ~~~~~~~~~~~~~~~~~~~~^
/Users/runner/work/iceberg-cpp/iceberg-cpp/build/_deps/sparrow-src/include/sparrow/layout/variable_size_binary_layout/variable_size_binary_array.hpp:683:70: error: no member named 'join' in namespace 'std::ranges::views'
        const auto joined_repeated_value_range = std::ranges::views::join(my_repeat_view);
                                                 ~~~~~~~~~~~~~~~~~~~~^
5 errors generated.
```

There are some other minor issues:

1. It should use `PREPEND` not `APPEND` at this line: https://github.com/man-group/sparrow/blob/532bf486243fc396f7a9392820fa7a77071782ad/CMakeLists.txt#L50. Otherwise I have to add `list(PREPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_BINARY_DIR}/_deps/sparrow-src/cmake)` on my side when using `FetchContent` to vendor sparrow to avoid error `include could not find requested file: sanitizers`.
2. It would be good to add a namespace `sparrow::` when installing the exported config file at https://github.com/man-group/sparrow/blob/532bf486243fc396f7a9392820fa7a77071782ad/CMakeLists.txt#L354.

These are not blocking issues at the moment. I need more time to get familiar with its API and best practice. Just want to report what I have found so far. @JohanMabille @Alex-PLACET @pitrou

**Comment by JohanMabille** [comment]
Hi there,

Thanks for the test and report! We get same issues when trying to build and use sparrow in WASM and are pushing fixes for that (more specifically, the target_compile_definitions that are missing). I'll take the opportunity to fix the other issues you faced, we will release a new version right after.

**Review by lidavidm — APPROVED** [review]
Presumably in the end we're only going to want one of the two libraries, right? It seems weird to potentially link up to 4 separate Arrow implementations in one project...

**Comment by wgtmac** [comment]
@lidavidm Yes, this is for the nanoarrow and sparrow comparison and finally one of them will be only used internally by the `libiceberg`. If `libiceberg` is pluggable enough, I think we can also remove the `libiceberg-arrow` and thus the dependency of arrow.

Let me fix the CI first. Then I think we need reach a consensus to choose one.

**Comment by lidavidm** [comment]
IMO, it's going to be hard/pointless to choose one until we actually write code that needs it. I hope we can get the ball rolling sooner rather than later on actual implementation/binding work

**Comment by wgtmac** [comment]
> 1/4 Test #1: arrow_unittest ...................Exit code 0xc0000135
***Exception:   0.01 sec

I have run into an error: https://github.com/apache/iceberg-cpp/actions/runs/13943870527/job/39026477819. It seems that I can get rid of it by removing the `sparrow` dependency. So I'm inclined to use `nanoarrow` for now and revisit this issue in the future.

I will polish this PR to depend on only `nanoarrow`. As the next step, I can add a conversion between `ArrowSchema` and the Iceberg schema. WDYT? @lidavidm @zhjwpku @Fokko

**Comment by lidavidm** [comment]
Sounds good to me

**Comment by zhjwpku** [comment]
Agreed, nanoarrow sounds good to me.

**Review by zhjwpku — APPROVED** [review]
LGTM, thanks for working on this.

**Comment by wgtmac** [comment]
@Xuanwo @Fokko Could you help review this?

**Comment by Fokko** [comment]
This looks good to me, thanks @wgtmac for working on this, and thanks @lidavidm and @zhjwpku for the review 👍

**Comment by wgtmac** [comment]
Thank you, @Fokko!
